### ISSUE TITLE
image contrast is wrong

### ISSUE THREAD

**Issue by cjbayliss** [cjbayliss/dark-mode-list#1]
for some reason doing this does not revert images back to the original values:

```css
html {
  filter: invert(95%);
}
img {
  filter: invert(95%);
}
```
